### ISSUE TITLE
Travis CI status check failing

### ISSUE THREAD

**Issue by deric4** [dev-sec/cis-dil-benchmark#98]
**Describe the bug**
Pull Requests are failing the Travis CI check because of a ruby version conflict between the [Travis CI build environment configuration (ruby 2.4.5)](https://github.com/dev-sec/cis-dil-benchmark/blob/master/.travis.yml#L5) and a newly added  (2020-11-26) ruby version requirement in [`chef-utils` (ruby 2.6)](https://github.com/chef/chef/blob/master/CHANGELOG.md#v16761-2020-11-26)

**Expected behavior**
The Travis CI Check should not fail because of environment misconfiguration.

**Actual behavior**

Logs from #97 
https://travis-ci.org/github/dev-sec/cis-dil-benchmark/builds/751236578#L248-L249

**Example code**

N/A: see travis build logs

**OS / Environment**

N/A: see travis build logs

**Inspec Version**

```paste below

```

**Baseline Version**

```paste below

```

**Additional context**
updating the `.travis.yml` to something like the following should resolve the error:
```yaml
---
dist: bionic
language: ruby
cache: bundler
rvm:
  - 2.6

bundler_args: --without integration
script: bundle exec rake
```
